version: '2'
services:

  web:
    container_name: base-api
    build: docker/dev
    ports:
      - $PORT:$PORT
      - "3229:9229"
    env_file:
      - .env
    volumes:
      - .:/server
    links:
      - database

  database:
    container_name: base-database
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
